# This workflow will run a suite of tests using the PySys system test framework

name: PySys

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      # Disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false
      
      matrix:
        # A selection range of OS, Python and Java versions
        include:
          - test-run-id: ubuntu-java8-py3.6
            os: ubuntu-latest
            java-version: 8
            python-version: 3.6
            
          #- test-run-id: macos-java14-py3.8
          #  os: macos-latest
          #  java-version: 14
          #  python-version: 3.8

          #- test-run-id: win-java8-py3.6
          #  os: windows-latest
          #  java-version: 8
          #  python-version: 3.6

          - test-run-id: win-java14-py3.8
            os: windows-latest
            java-version: 14
            python-version: 3.8
            
    runs-on: ${{matrix.os}}
    
    steps:
      # Install the desired version of Python and PySys
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java-version}}
          java-package: jdk
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ matrix.test-run-id }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ matrix.test-run-id }}-m2

      - name: Download testing dependencies with Maven
        run: mvn initialize --file pom.xml

      - name: Build sample with Maven
        run: mvn package --file sample/pom.xml -DskipTests

      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
          
      - name: Cache Python deps (get location)
        id: pip-cache
        run: |
            python -m pip install -U "pip>=20.1"
            echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache Python deps
        uses: actions/cache@v2
        with:
            path: ${{ steps.pip-cache.outputs.dir }}
            key: ${{ matrix.test-run-id }}-pip

      - name: Python dependencies - install
        id: deps
        run: |
          python -m pip install --upgrade pip
          pip install pysys==1.6.1

          # Use older version of coverage as 5.0 requires an SQLite version that doesn't work on this macos image currently
          pip install coverage==4.5.4

      - name: Test with PySys
        working-directory: test
        shell: bash
        id: pysys
        run: |
          python -m pysys run --ci --outdir=${{matrix.test-run-id}}
        
      # If any tests fail, PySys will return an error code, so we need "if: always()" so the following steps will run

      - name: Upload Python code coverage
        uses: codecov/codecov-action@v1
        if: always() && steps.pysys.outputs.artifact_PythonCoverageDir
        with:
          file: test/__coverage_python.${{matrix.test-run-id}}/coverage.xml
      
      - name: Upload performance CSV artifacts
        uses: actions/upload-artifact@v2
        # Only do this if some performance results were generated
        if: always() && steps.pysys.outputs.artifact_CSVPerformanceReport

        with:
          name: pysys_performance_${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.artifact_CSVPerformanceReport }}

      - name: Upload archive artifacts for any test failures
        uses: actions/upload-artifact@v2
        if: always() && steps.pysys.outputs.artifact_TestOutputArchiveDir

        with:
          name: pysys_output_${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.artifact_TestOutputArchiveDir }}
