# This workflow is for testing the PySys-Java plugins

name: PySys-Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      # Disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false
      
      matrix:
        # A selection range of OS, Python and Java versions
        include:
          - test-run-id: ubuntu-java8-py3.7
            os: ubuntu-latest
            java-version: 8
            python-version: "3.7"
          
          - test-run-id: macos-java14-py3.8
            os: macos-latest
            java-version: 14
            python-version: 3.8

          - test-run-id: win-java8-py3.7
            os: windows-latest
            java-version: 8
            python-version: "3.7"

          - test-run-id: win-java14-py3.10
            os: windows-latest
            java-version: 14
            python-version: "3.10"
            
    runs-on: ${{matrix.os}}
    
    steps:
      # Install the desired version of Python and PySys
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java-version}}
          java-package: jdk
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ matrix.test-run-id }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ matrix.test-run-id }}-m2

      - name: Download testing dependencies with Maven
        run: mvn initialize --file pom.xml

      - name: Build sample with Maven
        run: mvn package --file sample/pom.xml -DskipTests

      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
          
      - name: Cache Python deps (get location)
        id: pip-cache
        run: |
            python -m pip install -U "pip>=20.1"
            echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache Python deps
        uses: actions/cache@v2
        with:
            path: ${{ steps.pip-cache.outputs.dir }}
            key: ${{ matrix.test-run-id }}-pip

      - name: Python dependencies - install
        id: deps
        shell: bash
        run: |
          python -m pip install --upgrade setuptools wheel
          pip install pysys==2.0
          
          # Check it can be built and installed
          python setup.py bdist_wheel
          pip install dist/*.whl
          pip uninstall --yes PySys-Java

          pip install coverage==6.2

      - name: Test with PySys
        working-directory: test
        shell: bash
        id: pysys
        run: |
          PYTHONPATH=.. python -m pysys run --ci --outdir=${{matrix.test-run-id}}

      - name: Upload Python package .whl
        uses: actions/upload-artifact@v2
        with:
          name: installation_package
          path: dist/*.whl

      - name: Upload Python code coverage 
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # 2021-09 v2.1.0
        if: always() && steps.pysys.outputs.artifact_PythonCoverageDir
        with:
          name: ${{matrix.test-run-id}}
          directory: ${{ steps.pysys.outputs.artifact_PythonCoverageDir }}
        
      # If any tests fail, PySys will return an error code, so we need "if: always()" so the following steps will run

      - name: Upload performance CSV artifacts
        uses: actions/upload-artifact@v2
        # Only do this if some performance results were generated
        if: always() && steps.pysys.outputs.artifact_CSVPerformanceReport

        with:
          name: pysys_performance_${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.artifact_CSVPerformanceReport }}

      - name: Upload archive artifacts for any test failures
        uses: actions/upload-artifact@v2
        if: always() && steps.pysys.outputs.artifact_TestOutputArchiveDir

        with:
          name: pysys_output_${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.artifact_TestOutputArchiveDir }}
